# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05918dcff0fdd5596910017adcd958f621b9b2af409146fd69a4c9fffd066eb2b91e3532bed4a1f9d3753bd3e6d6c53b291f1a3d0de62b2c379c303a22ad56a6

test:
  secret_key_base: cb771f2451420fe5029cfe1de4152a54eef3106c41414f9f80b66d7a1735b475352d7b6c048ae160fe45ad8223f5e6b9580c14a0af0cde75be478e80c5868b11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
